/* External dependencies */
import 'package:flutter/cupertino.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

abstract class AppTextStyle {
  static TextStyle light9 =
      TextStyle(fontSize: 9.sp, fontWeight: FontWeight.w300);
  static TextStyle light10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w300);
  static TextStyle light12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w300);
  static TextStyle light13 =
      TextStyle(fontSize: 13.sp, fontWeight: FontWeight.w300);
  static TextStyle light14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w300);
  static TextStyle light15 =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w300);
  static TextStyle light16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w300);
  static TextStyle light18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w300);
  static TextStyle light20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w300);
  static TextStyle light22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w300);
  static TextStyle light23 =
      TextStyle(fontSize: 23.sp, fontWeight: FontWeight.w300);
  static TextStyle light24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w300);
  static TextStyle light28 =
      TextStyle(fontSize: 28.sp, fontWeight: FontWeight.w300);
  static TextStyle light30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w300);
  static TextStyle light32 =
      TextStyle(fontSize: 32.sp, fontWeight: FontWeight.w300);
  static TextStyle light34 =
      TextStyle(fontSize: 34.sp, fontWeight: FontWeight.w300);
  static TextStyle light36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w300);
  static TextStyle light45 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w300);
  static TextStyle light48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w300);
  static TextStyle regular9 =
      TextStyle(fontSize: 9.sp, fontWeight: FontWeight.w400);
  static TextStyle regular10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w400);
  static TextStyle regular11 =
      TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w400);
  static TextStyle regular12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w400);
  static TextStyle regular14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w400);
  static TextStyle regular15 =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w400);
  static TextStyle regular16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w400);
  static TextStyle regular17 =
      TextStyle(fontSize: 17.sp, fontWeight: FontWeight.w400);
  static TextStyle regular18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w400);
  static TextStyle regular20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w400);
  static TextStyle regular22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w400);
  static TextStyle regular23 =
      TextStyle(fontSize: 23.sp, fontWeight: FontWeight.w400);
  static TextStyle regular24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w400);
  static TextStyle regular28 =
      TextStyle(fontSize: 28.sp, fontWeight: FontWeight.w400);
  static TextStyle regular30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w400);
  static TextStyle regular32 =
      TextStyle(fontSize: 32.sp, fontWeight: FontWeight.w400);
  static TextStyle regular34 =
      TextStyle(fontSize: 34.sp, fontWeight: FontWeight.w400);
  static TextStyle regular36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w400);
  static TextStyle regular45 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w400);
  static TextStyle regular48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w400);
  static TextStyle medium8 =
      TextStyle(fontSize: 8.sp, fontWeight: FontWeight.w500);
  static TextStyle medium10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w500);
  static TextStyle medium12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w500);
  static TextStyle medium14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w500);
  static TextStyle medium16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w500);
  static TextStyle medium18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w500);
  static TextStyle medium20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w500);
  static TextStyle medium22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w500);
  static TextStyle medium24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w500);
  static TextStyle medium30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w500);
  static TextStyle medium32 =
      TextStyle(fontSize: 32.sp, fontWeight: FontWeight.w500);
  static TextStyle medium36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w500);
  static TextStyle medium45 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w500);
  static TextStyle medium48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w500);

  static TextStyle normal10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w600);
  static TextStyle normal12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w600);
  static TextStyle normal14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w600);
  static TextStyle normal16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w600);
  static TextStyle normal18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w600);
  static TextStyle normal20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w600);
  static TextStyle normal22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w600);
  static TextStyle normal24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w600);
  static TextStyle normal30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w600);
  static TextStyle normal32 =
      TextStyle(fontSize: 32.sp, fontWeight: FontWeight.w600);
  static TextStyle normal36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w600);
  static TextStyle normal45 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w600);
  static TextStyle normal48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w600);

  static TextStyle bold10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w700);
  static TextStyle bold11 =
      TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w700);
  static TextStyle bold12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w700);
  static TextStyle bold14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w700);
  static TextStyle bold15 =
      TextStyle(fontSize: 15.sp, fontWeight: FontWeight.w700);
  static TextStyle bold16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w700);
  static TextStyle bold17 =
      TextStyle(fontSize: 17.sp, fontWeight: FontWeight.w700);
  static TextStyle bold18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w700);
  static TextStyle bold19 =
      TextStyle(fontSize: 19.sp, fontWeight: FontWeight.w700);
  static TextStyle bold20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w700);
  static TextStyle bold21 =
      TextStyle(fontSize: 21.sp, fontWeight: FontWeight.w700);
  static TextStyle bold22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w700);
  static TextStyle bold24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w700);
  static TextStyle bold26 =
      TextStyle(fontSize: 26.sp, fontWeight: FontWeight.w700);
  static TextStyle bold28 =
      TextStyle(fontSize: 28.sp, fontWeight: FontWeight.w700);
  static TextStyle bold30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w700);
  static TextStyle bold34 =
      TextStyle(fontSize: 34.sp, fontWeight: FontWeight.w700);
  static TextStyle bold36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w700);
  static TextStyle bold40 =
      TextStyle(fontSize: 40.sp, fontWeight: FontWeight.w700);
  static TextStyle bold48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w700);

  static TextStyle bolder10 =
      TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder12 =
      TextStyle(fontSize: 12.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder14 =
      TextStyle(fontSize: 14.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder16 =
      TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder18 =
      TextStyle(fontSize: 18.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder20 =
      TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder22 =
      TextStyle(fontSize: 22.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder24 =
      TextStyle(fontSize: 24.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder26 =
      TextStyle(fontSize: 26.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder28 =
      TextStyle(fontSize: 28.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder30 =
      TextStyle(fontSize: 30.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder36 =
      TextStyle(fontSize: 36.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder40 =
      TextStyle(fontSize: 40.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder45 =
      TextStyle(fontSize: 45.sp, fontWeight: FontWeight.w800);
  static TextStyle bolder48 =
      TextStyle(fontSize: 48.sp, fontWeight: FontWeight.w800);
}
